"""empty message

Revision ID: 310caab68594
Revises: c6f9dd58413d
Create Date: 2026-03-24 13:58:23.125489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310caab68594'
down_revision: Union[str, None] = 'c6f9dd58413d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_historico_criado_em', table_name='historico_pesquisas', postgresql_where='(deletado_em IS NULL)')
    op.create_index('idx_historico_criado_em', 'historico_pesquisas', ['criado_em'], unique=False, postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_index('idx_historico_usuario_criado', table_name='historico_pesquisas', postgresql_where='(deletado_em IS NULL)')
    op.create_index('idx_historico_usuario_criado', 'historico_pesquisas', ['usuario', 'criado_em'], unique=False, postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_historico_usuario_criado', table_name='historico_pesquisas', postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('idx_historico_usuario_criado', 'historico_pesquisas', ['usuario', sa.text('criado_em DESC')], unique=False, postgresql_where='(deletado_em IS NULL)')
    op.drop_index('idx_historico_criado_em', table_name='historico_pesquisas', postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('idx_historico_criado_em', 'historico_pesquisas', [sa.text('criado_em DESC')], unique=False, postgresql_where='(deletado_em IS NULL)')
    # ### end Alembic commands ###
