"""empty message

Revision ID: 5180e6402780
Revises: f2a51ee6c308
Create Date: 2026-03-13 02:56:48.127271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5180e6402780'
down_revision: Union[str, None] = 'f2a51ee6c308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_historico_criado_em', table_name='historico_pesquisas', postgresql_where='(deletado_em IS NULL)')
    op.create_index('idx_historico_criado_em', 'historico_pesquisas', ['criado_em'], unique=False, postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_index('idx_historico_usuario_criado', table_name='historico_pesquisas', postgresql_where='(deletado_em IS NULL)')
    op.create_index('idx_historico_usuario_criado', 'historico_pesquisas', ['usuario', 'criado_em'], unique=False, postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.add_column('tags', sa.Column('equipe_id', sa.UUID(), nullable=True, comment='ID da equipe dona do grupo (NULL = grupo pessoal)'))
    op.alter_column('tags', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico do grupo',
               existing_comment='Identificador único da tag',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('tags', 'nome',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome do grupo',
               existing_comment='Nome da tag',
               existing_nullable=False)
    op.alter_column('tags', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               comment='Usuario que criou o grupo',
               existing_comment='Usuário proprietário da tag',
               existing_nullable=False)
    op.alter_column('tags', 'cor',
               existing_type=sa.VARCHAR(length=7),
               comment='Cor hex do grupo (ex: #3B82F6)',
               existing_comment='Cor hex da tag (ex: #3B82F6)',
               existing_nullable=True)
    op.alter_column('tags', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criacao',
               existing_comment='Data e hora de criação',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tags', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da ultima atualizacao',
               existing_comment='Data e hora da última atualização',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tags', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da exclusao (soft delete)',
               existing_comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.create_index('idx_tags_equipe_id', 'tags', ['equipe_id'], unique=False, postgresql_where=sa.text('deletado_em IS NULL AND equipe_id IS NOT NULL'))
    op.create_index('uq_tags_equipe_nome', 'tags', ['equipe_id', 'nome'], unique=True, postgresql_where=sa.text('deletado_em IS NULL AND equipe_id IS NOT NULL'))
    op.create_foreign_key(None, 'tags', 'equipes', ['equipe_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'tags',
        'Tabela de grupos de processos (pessoais ou de equipe)',
        existing_comment='Tabela de tags para agrupamento de processos salvos',
        schema=None
    )
    op.alter_column('team_tags', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico da tag',
               existing_comment='Identificador unico da team tag',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('team_tags', 'equipe_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='ID da equipe dona da tag (NULL = tag pessoal)',
               existing_comment='ID da equipe dona da tag')
    op.create_index('idx_team_tag_pessoal', 'team_tags', ['criado_por'], unique=False, postgresql_where=sa.text('deletado_em IS NULL AND equipe_id IS NULL'))
    op.create_index('uq_team_tag_pessoal_nome', 'team_tags', ['criado_por', 'nome'], unique=True, postgresql_where=sa.text('deletado_em IS NULL AND equipe_id IS NULL'))
    op.create_table_comment(
        'team_tags',
        'Tags para rotular processos (pessoais ou de equipe)',
        existing_comment='Tags de equipe para rotular processos no kanban',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'team_tags',
        'Tags de equipe para rotular processos no kanban',
        existing_comment='Tags para rotular processos (pessoais ou de equipe)',
        schema=None
    )
    op.drop_index('uq_team_tag_pessoal_nome', table_name='team_tags', postgresql_where=sa.text('deletado_em IS NULL AND equipe_id IS NULL'))
    op.drop_index('idx_team_tag_pessoal', table_name='team_tags', postgresql_where=sa.text('deletado_em IS NULL AND equipe_id IS NULL'))
    op.alter_column('team_tags', 'equipe_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='ID da equipe dona da tag',
               existing_comment='ID da equipe dona da tag (NULL = tag pessoal)')
    op.alter_column('team_tags', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico da team tag',
               existing_comment='Identificador unico da tag',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_table_comment(
        'tags',
        'Tabela de tags para agrupamento de processos salvos',
        existing_comment='Tabela de grupos de processos (pessoais ou de equipe)',
        schema=None
    )
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_index('uq_tags_equipe_nome', table_name='tags', postgresql_where=sa.text('deletado_em IS NULL AND equipe_id IS NOT NULL'))
    op.drop_index('idx_tags_equipe_id', table_name='tags', postgresql_where=sa.text('deletado_em IS NULL AND equipe_id IS NOT NULL'))
    op.alter_column('tags', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da exclusão (soft delete)',
               existing_comment='Data e hora da exclusao (soft delete)',
               existing_nullable=True)
    op.alter_column('tags', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da última atualização',
               existing_comment='Data e hora da ultima atualizacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tags', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criação',
               existing_comment='Data e hora de criacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tags', 'cor',
               existing_type=sa.VARCHAR(length=7),
               comment='Cor hex da tag (ex: #3B82F6)',
               existing_comment='Cor hex do grupo (ex: #3B82F6)',
               existing_nullable=True)
    op.alter_column('tags', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               comment='Usuário proprietário da tag',
               existing_comment='Usuario que criou o grupo',
               existing_nullable=False)
    op.alter_column('tags', 'nome',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome da tag',
               existing_comment='Nome do grupo',
               existing_nullable=False)
    op.alter_column('tags', 'id',
               existing_type=sa.UUID(),
               comment='Identificador único da tag',
               existing_comment='Identificador unico do grupo',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('tags', 'equipe_id')
    op.drop_index('idx_historico_usuario_criado', table_name='historico_pesquisas', postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('idx_historico_usuario_criado', 'historico_pesquisas', ['usuario', sa.text('criado_em DESC')], unique=False, postgresql_where='(deletado_em IS NULL)')
    op.drop_index('idx_historico_criado_em', table_name='historico_pesquisas', postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('idx_historico_criado_em', 'historico_pesquisas', [sa.text('criado_em DESC')], unique=False, postgresql_where='(deletado_em IS NULL)')
    # ### end Alembic commands ###
