"""empty message

Revision ID: a3d9a223862b
Revises: e6cb5e1662cc
Create Date: 2026-03-16 21:38:52.070903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3d9a223862b'
down_revision: Union[str, None] = 'e6cb5e1662cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_horas_andamento',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('orgao', sa.String(length=100), nullable=False),
    sa.Column('grupo_key', sa.String(length=50), nullable=False),
    sa.Column('horas', sa.Float(), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('atualizado_por', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_orgao_grupo', 'configuracao_horas_andamento', ['orgao', 'grupo_key'], unique=True)
    op.create_table('fluxos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador unico do fluxo'),
    sa.Column('nome', sa.String(length=200), nullable=False, comment='Nome do fluxo'),
    sa.Column('descricao', sa.Text(), nullable=True, comment='Descricao do fluxo'),
    sa.Column('usuario', sa.String(length=100), nullable=False, comment='Usuario criador do fluxo'),
    sa.Column('equipe_id', sa.UUID(), nullable=True, comment='Equipe dona do fluxo (NULL = pessoal)'),
    sa.Column('orgao', sa.String(length=50), nullable=True, comment='Orgao para fluxo organizacional (NULL = nao-org)'),
    sa.Column('versao', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Versao para controle de concorrencia otimista'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'rascunho'"), nullable=False, comment='Status do fluxo: rascunho, publicado, arquivado'),
    sa.Column('viewport', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Viewport do canvas {x, y, zoom}'),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Data e hora de criacao'),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Data e hora da ultima atualizacao'),
    sa.Column('deletado_em', sa.TIMESTAMP(timezone=True), nullable=True, comment='Data e hora da exclusao (soft delete)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Fluxos de processos (workflow templates)'
    )
    op.create_index('idx_fluxo_equipe', 'fluxos', ['equipe_id'], unique=False, postgresql_where=sa.text('deletado_em IS NULL AND equipe_id IS NOT NULL'))
    op.create_index('idx_fluxo_orgao', 'fluxos', ['orgao'], unique=False, postgresql_where=sa.text('deletado_em IS NULL AND orgao IS NOT NULL'))
    op.create_index('idx_fluxo_usuario', 'fluxos', ['usuario'], unique=False, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_table('fluxo_edges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador unico da edge'),
    sa.Column('fluxo_id', sa.UUID(), nullable=False, comment='Fluxo ao qual a edge pertence'),
    sa.Column('edge_id', sa.String(length=100), nullable=False, comment='ID do React Flow (client-side)'),
    sa.Column('source_node_id', sa.String(length=100), nullable=False, comment='node_id de origem'),
    sa.Column('target_node_id', sa.String(length=100), nullable=False, comment='node_id de destino'),
    sa.Column('tipo', sa.String(length=30), server_default=sa.text("'padrao'"), nullable=False, comment='Tipo da edge: padrao, condicional, loop'),
    sa.Column('label', sa.String(length=200), nullable=True, comment='Texto de exibicao na edge'),
    sa.Column('condicao', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Condicao para edges condicionais {campo, operador, valor}'),
    sa.Column('ordem', sa.Integer(), nullable=True, comment='Ordem das edges de saida de um node de decisao'),
    sa.Column('animated', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Se a edge deve ser animada'),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Data e hora de criacao'),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Data e hora da ultima atualizacao'),
    sa.Column('deletado_em', sa.TIMESTAMP(timezone=True), nullable=True, comment='Data e hora da exclusao (soft delete)'),
    sa.ForeignKeyConstraint(['fluxo_id'], ['fluxos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Edges (conexoes) de um fluxo de processo'
    )
    op.create_index('idx_fluxo_edge_fluxo', 'fluxo_edges', ['fluxo_id'], unique=False, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('uq_fluxo_edge_id', 'fluxo_edges', ['fluxo_id', 'edge_id'], unique=True, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_table('fluxo_nodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador unico do node'),
    sa.Column('fluxo_id', sa.UUID(), nullable=False, comment='Fluxo ao qual o node pertence'),
    sa.Column('node_id', sa.String(length=100), nullable=False, comment='ID do React Flow (client-side)'),
    sa.Column('tipo', sa.String(length=30), nullable=False, comment='Tipo do node: sei_task, etapa, decisao, inicio, fim, fork, join'),
    sa.Column('nome', sa.String(length=300), nullable=False, comment='Nome/label do node'),
    sa.Column('descricao', sa.Text(), nullable=True, comment='Descricao do node'),
    sa.Column('sei_task_key', sa.String(length=50), nullable=True, comment='Chave do TASK_GROUPS para nodes do tipo sei_task'),
    sa.Column('responsavel', sa.String(length=200), nullable=True, comment='Responsavel pela etapa'),
    sa.Column('duracao_estimada_horas', sa.Float(), nullable=True, comment='Duracao estimada em horas'),
    sa.Column('prioridade', sa.String(length=20), nullable=True, comment='Prioridade: baixa, media, alta, critica'),
    sa.Column('documentos_necessarios', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Lista de documentos necessarios'),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Lista de checklist items'),
    sa.Column('regras_prazo', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Regras de prazo {dias_uteis, tipo}'),
    sa.Column('metadata_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Metadados arbitrarios key-value'),
    sa.Column('posicao_x', sa.Float(), nullable=False, comment='Posicao X no canvas'),
    sa.Column('posicao_y', sa.Float(), nullable=False, comment='Posicao Y no canvas'),
    sa.Column('largura', sa.Float(), nullable=True, comment='Largura do node no canvas'),
    sa.Column('altura', sa.Float(), nullable=True, comment='Altura do node no canvas'),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Data e hora de criacao'),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Data e hora da ultima atualizacao'),
    sa.Column('deletado_em', sa.TIMESTAMP(timezone=True), nullable=True, comment='Data e hora da exclusao (soft delete)'),
    sa.ForeignKeyConstraint(['fluxo_id'], ['fluxos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Nodes (etapas) de um fluxo de processo'
    )
    op.create_index('idx_fluxo_node_fluxo', 'fluxo_nodes', ['fluxo_id'], unique=False, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('uq_fluxo_node_id', 'fluxo_nodes', ['fluxo_id', 'node_id'], unique=True, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_table('fluxo_processos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador unico da vinculacao'),
    sa.Column('fluxo_id', sa.UUID(), nullable=False, comment='Fluxo vinculado'),
    sa.Column('numero_processo', sa.String(length=50), nullable=False, comment='Numero do processo (sem formatacao)'),
    sa.Column('numero_processo_formatado', sa.String(length=50), nullable=True, comment='Numero do processo formatado'),
    sa.Column('node_atual_id', sa.String(length=100), nullable=True, comment='node_id da etapa atual do processo no fluxo'),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'em_andamento'"), nullable=False, comment='Status: em_andamento, concluido, pausado, cancelado'),
    sa.Column('iniciado_em', sa.TIMESTAMP(timezone=True), nullable=True, comment='Data e hora de inicio do processo no fluxo'),
    sa.Column('concluido_em', sa.TIMESTAMP(timezone=True), nullable=True, comment='Data e hora de conclusao'),
    sa.Column('atribuido_por', sa.String(length=100), nullable=False, comment='Usuario que atribuiu o processo ao fluxo'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas sobre a vinculacao'),
    sa.Column('historico', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True, comment='Historico de movimentacoes [{node_id, entrada_em, saida_em, usuario}]'),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Data e hora de criacao'),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Data e hora da ultima atualizacao'),
    sa.Column('deletado_em', sa.TIMESTAMP(timezone=True), nullable=True, comment='Data e hora da exclusao (soft delete)'),
    sa.ForeignKeyConstraint(['fluxo_id'], ['fluxos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Vinculacao de processos a fluxos'
    )
    op.create_index('idx_fluxo_processo_fluxo', 'fluxo_processos', ['fluxo_id'], unique=False, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('idx_fluxo_processo_numero', 'fluxo_processos', ['numero_processo'], unique=False, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('uq_fluxo_processo', 'fluxo_processos', ['fluxo_id', 'numero_processo'], unique=True, postgresql_where=sa.text('deletado_em IS NULL'))
    op.add_column('credenciais_usuario', sa.Column('papel_global', sa.String(length=20), server_default=sa.text("'user'"), nullable=False, comment='Papel global do usuário (admin, beta, user)'))
    op.drop_index('idx_historico_criado_em', table_name='historico_pesquisas', postgresql_where='(deletado_em IS NULL)')
    op.create_index('idx_historico_criado_em', 'historico_pesquisas', ['criado_em'], unique=False, postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_index('idx_historico_usuario_criado', table_name='historico_pesquisas', postgresql_where='(deletado_em IS NULL)')
    op.create_index('idx_historico_usuario_criado', 'historico_pesquisas', ['usuario', 'criado_em'], unique=False, postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_historico_usuario_criado', table_name='historico_pesquisas', postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('idx_historico_usuario_criado', 'historico_pesquisas', ['usuario', sa.text('criado_em DESC')], unique=False, postgresql_where='(deletado_em IS NULL)')
    op.drop_index('idx_historico_criado_em', table_name='historico_pesquisas', postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('idx_historico_criado_em', 'historico_pesquisas', [sa.text('criado_em DESC')], unique=False, postgresql_where='(deletado_em IS NULL)')
    op.drop_column('credenciais_usuario', 'papel_global')
    op.drop_index('uq_fluxo_processo', table_name='fluxo_processos', postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_index('idx_fluxo_processo_numero', table_name='fluxo_processos', postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_index('idx_fluxo_processo_fluxo', table_name='fluxo_processos', postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_table('fluxo_processos')
    op.drop_index('uq_fluxo_node_id', table_name='fluxo_nodes', postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_index('idx_fluxo_node_fluxo', table_name='fluxo_nodes', postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_table('fluxo_nodes')
    op.drop_index('uq_fluxo_edge_id', table_name='fluxo_edges', postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_index('idx_fluxo_edge_fluxo', table_name='fluxo_edges', postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_table('fluxo_edges')
    op.drop_index('idx_fluxo_usuario', table_name='fluxos', postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_index('idx_fluxo_orgao', table_name='fluxos', postgresql_where=sa.text('deletado_em IS NULL AND orgao IS NOT NULL'))
    op.drop_index('idx_fluxo_equipe', table_name='fluxos', postgresql_where=sa.text('deletado_em IS NULL AND equipe_id IS NOT NULL'))
    op.drop_table('fluxos')
    op.drop_index('uq_orgao_grupo', table_name='configuracao_horas_andamento')
    op.drop_table('configuracao_horas_andamento')
    # ### end Alembic commands ###
