"""empty message

Revision ID: b8b670b34a33
Revises: ac0daeb93a96
Create Date: 2026-03-23 11:43:00.173504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8b670b34a33'
down_revision: Union[str, None] = 'ac0daeb93a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tipo_documento_nome', table_name='tipos_documento')
    op.drop_table('tipos_documento')
    op.drop_index('idx_historico_criado_em', table_name='historico_pesquisas', postgresql_where='(deletado_em IS NULL)')
    op.create_index('idx_historico_criado_em', 'historico_pesquisas', ['criado_em'], unique=False, postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_index('idx_historico_usuario_criado', table_name='historico_pesquisas', postgresql_where='(deletado_em IS NULL)')
    op.create_index('idx_historico_usuario_criado', 'historico_pesquisas', ['usuario', 'criado_em'], unique=False, postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.alter_column('unidades_sei', 'id_unidade',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='ID da unidade no SEI',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unidades_sei', 'id_unidade',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='ID da unidade no SEI',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_historico_usuario_criado', table_name='historico_pesquisas', postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('idx_historico_usuario_criado', 'historico_pesquisas', ['usuario', sa.text('criado_em DESC')], unique=False, postgresql_where='(deletado_em IS NULL)')
    op.drop_index('idx_historico_criado_em', table_name='historico_pesquisas', postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('idx_historico_criado_em', 'historico_pesquisas', [sa.text('criado_em DESC')], unique=False, postgresql_where='(deletado_em IS NULL)')
    op.create_table('tipos_documento',
    sa.Column('id_tipo_documento', sa.BIGINT(), autoincrement=True, nullable=False, comment='ID do tipo de documento no SEI'),
    sa.Column('nome', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='Nome do tipo de documento'),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='Data e hora de criação'),
    sa.PrimaryKeyConstraint('id_tipo_documento', name='tipos_documento_pkey'),
    comment='Tipos de documento do SEI'
    )
    op.create_index('idx_tipo_documento_nome', 'tipos_documento', ['nome'], unique=False)
    # ### end Alembic commands ###
