"""empty message

Revision ID: f2a51ee6c308
Revises: 010_add_cpf_credenciais
Create Date: 2026-03-06 13:27:06.655018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2a51ee6c308'
down_revision: Union[str, None] = '010_add_cpf_credenciais'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processo_situacoes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador unico'),
    sa.Column('numero_processo', sa.String(length=50), nullable=False, comment='Numero do processo sem formatacao'),
    sa.Column('total_andamentos', sa.Integer(), nullable=False, comment='TotalItens de andamentos no momento da geracao'),
    sa.Column('ultimo_andamento_id', sa.String(length=50), nullable=True, comment='ID do ultimo andamento como referencia'),
    sa.Column('conteudo', sa.Text(), nullable=False, comment='Texto da situacao atual gerada por IA'),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Data e hora de criacao'),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Data e hora da ultima atualizacao'),
    sa.Column('deletado_em', sa.TIMESTAMP(timezone=True), nullable=True, comment='Data e hora da exclusao (soft delete)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Situacao atual de processos gerada por IA'
    )
    op.create_index('idx_situacao_processo_unique', 'processo_situacoes', ['numero_processo'], unique=True, postgresql_where=sa.text('deletado_em IS NULL'))
    op.alter_column('compartilhamentos', 'id',
               existing_type=sa.UUID(),
               comment='Identificador único do compartilhamento',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('compartilhamentos', 'tag_id',
               existing_type=sa.UUID(),
               comment='ID da tag compartilhada',
               existing_nullable=False)
    op.alter_column('compartilhamentos', 'compartilhado_por',
               existing_type=sa.VARCHAR(length=100),
               comment='Usuário que compartilhou',
               existing_nullable=False)
    op.alter_column('compartilhamentos', 'equipe_destino_id',
               existing_type=sa.UUID(),
               comment='ID da equipe destino (se compartilhamento com equipe)',
               existing_nullable=True)
    op.alter_column('compartilhamentos', 'usuario_destino',
               existing_type=sa.VARCHAR(length=100),
               comment='Usuário destino (se compartilhamento individual)',
               existing_nullable=True)
    op.alter_column('compartilhamentos', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criação',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('compartilhamentos', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.alter_column('equipe_membros', 'id',
               existing_type=sa.UUID(),
               comment='Identificador único do membro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('equipe_membros', 'equipe_id',
               existing_type=sa.UUID(),
               comment='ID da equipe',
               existing_nullable=False)
    op.alter_column('equipe_membros', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               comment='Identificação do usuário membro',
               existing_nullable=False)
    op.alter_column('equipe_membros', 'papel',
               existing_type=sa.VARCHAR(length=20),
               comment='Papel do membro na equipe (admin, member)',
               existing_nullable=False,
               existing_server_default=sa.text("'member'::character varying"))
    op.alter_column('equipe_membros', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criação',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('equipe_membros', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.alter_column('equipes', 'id',
               existing_type=sa.UUID(),
               comment='Identificador único da equipe',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('equipes', 'nome',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome da equipe',
               existing_nullable=False)
    op.alter_column('equipes', 'descricao',
               existing_type=sa.TEXT(),
               comment='Descrição da equipe',
               existing_nullable=True)
    op.alter_column('equipes', 'proprietario_usuario',
               existing_type=sa.VARCHAR(length=100),
               comment='Usuário proprietário da equipe',
               existing_nullable=False)
    op.alter_column('equipes', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criação',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('equipes', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da última atualização',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('equipes', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.alter_column('historico_pesquisas', 'id',
               existing_type=sa.UUID(),
               comment='Identificador único da pesquisa',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('historico_pesquisas', 'numero_processo',
               existing_type=sa.VARCHAR(length=50),
               comment='Número do processo sem formatação',
               existing_nullable=False)
    op.alter_column('historico_pesquisas', 'numero_processo_formatado',
               existing_type=sa.VARCHAR(length=50),
               comment='Número do processo formatado (ex: 12345.678901/2024-99)',
               existing_nullable=True)
    op.alter_column('historico_pesquisas', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               comment='Identificação do usuário (email, CPF, username, etc)',
               existing_nullable=False)
    op.alter_column('historico_pesquisas', 'caixa_contexto',
               existing_type=sa.TEXT(),
               comment='Campo de texto livre para contexto adicional',
               existing_nullable=True)
    op.alter_column('historico_pesquisas', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criação do registro',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('historico_pesquisas', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da última atualização',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('historico_pesquisas', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.drop_index('idx_historico_criado_em', table_name='historico_pesquisas', postgresql_where='(deletado_em IS NULL)')
    op.create_index('idx_historico_criado_em', 'historico_pesquisas', ['criado_em'], unique=False, postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_index('idx_historico_usuario_criado', table_name='historico_pesquisas', postgresql_where='(deletado_em IS NULL)')
    op.create_index('idx_historico_usuario_criado', 'historico_pesquisas', ['usuario', 'criado_em'], unique=False, postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_table_comment(
        'observacao_mencoes',
        existing_comment='Mencoes de usuarios em observacoes',
        schema=None
    )
    op.alter_column('observacoes', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico da observacao',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('observacoes', 'numero_processo',
               existing_type=sa.VARCHAR(length=50),
               comment='Numero do processo sem formatacao',
               existing_nullable=False)
    op.alter_column('observacoes', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               comment='Usuario autor da observacao',
               existing_nullable=False)
    op.alter_column('observacoes', 'equipe_id',
               existing_type=sa.UUID(),
               comment='ID da equipe (obrigatorio quando escopo=equipe)',
               existing_nullable=True)
    op.alter_column('observacoes', 'conteudo',
               existing_type=sa.TEXT(),
               comment='Conteudo da observacao',
               existing_nullable=False)
    op.alter_column('observacoes', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('observacoes', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da ultima atualizacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('observacoes', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da exclusao (soft delete)',
               existing_nullable=True)
    op.alter_column('processo_entendimentos', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico do entendimento',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('processo_entendimentos', 'numero_processo',
               existing_type=sa.VARCHAR(length=50),
               comment='Numero do processo sem formatacao',
               existing_nullable=False)
    op.alter_column('processo_entendimentos', 'conteudo',
               existing_type=sa.TEXT(),
               comment='Conteudo do entendimento gerado por IA',
               existing_nullable=False)
    op.alter_column('processo_entendimentos', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('processo_entendimentos', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da ultima atualizacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('processo_entendimentos', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da exclusao (soft delete)',
               existing_nullable=True)
    op.alter_column('processo_team_tags', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico da associacao',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('processo_team_tags', 'team_tag_id',
               existing_type=sa.UUID(),
               comment='ID da team tag',
               existing_nullable=False)
    op.alter_column('processo_team_tags', 'numero_processo',
               existing_type=sa.VARCHAR(length=50),
               comment='Numero do processo sem formatacao',
               existing_nullable=False)
    op.alter_column('processo_team_tags', 'adicionado_por',
               existing_type=sa.VARCHAR(length=100),
               comment='Usuario que associou a tag ao processo',
               existing_nullable=False)
    op.alter_column('processo_team_tags', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('processo_team_tags', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da exclusao (soft delete)',
               existing_nullable=True)
    op.alter_column('processos_salvos', 'id',
               existing_type=sa.UUID(),
               comment='Identificador único do processo salvo',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('processos_salvos', 'tag_id',
               existing_type=sa.UUID(),
               comment='ID da tag associada',
               existing_nullable=False)
    op.alter_column('processos_salvos', 'numero_processo',
               existing_type=sa.VARCHAR(length=50),
               comment='Número do processo sem formatação',
               existing_nullable=False)
    op.alter_column('processos_salvos', 'numero_processo_formatado',
               existing_type=sa.VARCHAR(length=50),
               comment='Número do processo formatado',
               existing_nullable=True)
    op.alter_column('processos_salvos', 'nota',
               existing_type=sa.TEXT(),
               comment='Nota opcional sobre o processo',
               existing_nullable=True)
    op.alter_column('processos_salvos', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criação',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('processos_salvos', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.alter_column('tags', 'id',
               existing_type=sa.UUID(),
               comment='Identificador único da tag',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('tags', 'nome',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome da tag',
               existing_nullable=False)
    op.alter_column('tags', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               comment='Usuário proprietário da tag',
               existing_nullable=False)
    op.alter_column('tags', 'cor',
               existing_type=sa.VARCHAR(length=7),
               comment='Cor hex da tag (ex: #3B82F6)',
               existing_nullable=True)
    op.alter_column('tags', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criação',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tags', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da última atualização',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tags', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.alter_column('team_tags', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico da team tag',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('team_tags', 'equipe_id',
               existing_type=sa.UUID(),
               comment='ID da equipe dona da tag',
               existing_nullable=False)
    op.alter_column('team_tags', 'nome',
               existing_type=sa.VARCHAR(length=100),
               comment='Nome da tag',
               existing_nullable=False)
    op.alter_column('team_tags', 'cor',
               existing_type=sa.VARCHAR(length=7),
               comment='Cor hex da tag (ex: #3B82F6)',
               existing_nullable=True)
    op.alter_column('team_tags', 'criado_por',
               existing_type=sa.VARCHAR(length=100),
               comment='Usuario que criou a tag',
               existing_nullable=False)
    op.alter_column('team_tags', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('team_tags', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da ultima atualizacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('team_tags', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora da exclusao (soft delete)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_tags', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da exclusao (soft delete)',
               existing_nullable=True)
    op.alter_column('team_tags', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da ultima atualizacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('team_tags', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora de criacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('team_tags', 'criado_por',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Usuario que criou a tag',
               existing_nullable=False)
    op.alter_column('team_tags', 'cor',
               existing_type=sa.VARCHAR(length=7),
               comment=None,
               existing_comment='Cor hex da tag (ex: #3B82F6)',
               existing_nullable=True)
    op.alter_column('team_tags', 'nome',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nome da tag',
               existing_nullable=False)
    op.alter_column('team_tags', 'equipe_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID da equipe dona da tag',
               existing_nullable=False)
    op.alter_column('team_tags', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico da team tag',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('tags', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.alter_column('tags', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da última atualização',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tags', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora de criação',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tags', 'cor',
               existing_type=sa.VARCHAR(length=7),
               comment=None,
               existing_comment='Cor hex da tag (ex: #3B82F6)',
               existing_nullable=True)
    op.alter_column('tags', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Usuário proprietário da tag',
               existing_nullable=False)
    op.alter_column('tags', 'nome',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nome da tag',
               existing_nullable=False)
    op.alter_column('tags', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador único da tag',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('processos_salvos', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.alter_column('processos_salvos', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora de criação',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('processos_salvos', 'nota',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Nota opcional sobre o processo',
               existing_nullable=True)
    op.alter_column('processos_salvos', 'numero_processo_formatado',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Número do processo formatado',
               existing_nullable=True)
    op.alter_column('processos_salvos', 'numero_processo',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Número do processo sem formatação',
               existing_nullable=False)
    op.alter_column('processos_salvos', 'tag_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID da tag associada',
               existing_nullable=False)
    op.alter_column('processos_salvos', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador único do processo salvo',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('processo_team_tags', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da exclusao (soft delete)',
               existing_nullable=True)
    op.alter_column('processo_team_tags', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora de criacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('processo_team_tags', 'adicionado_por',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Usuario que associou a tag ao processo',
               existing_nullable=False)
    op.alter_column('processo_team_tags', 'numero_processo',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Numero do processo sem formatacao',
               existing_nullable=False)
    op.alter_column('processo_team_tags', 'team_tag_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID da team tag',
               existing_nullable=False)
    op.alter_column('processo_team_tags', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico da associacao',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('processo_entendimentos', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da exclusao (soft delete)',
               existing_nullable=True)
    op.alter_column('processo_entendimentos', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da ultima atualizacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('processo_entendimentos', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora de criacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('processo_entendimentos', 'conteudo',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Conteudo do entendimento gerado por IA',
               existing_nullable=False)
    op.alter_column('processo_entendimentos', 'numero_processo',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Numero do processo sem formatacao',
               existing_nullable=False)
    op.alter_column('processo_entendimentos', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico do entendimento',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('observacoes', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da exclusao (soft delete)',
               existing_nullable=True)
    op.alter_column('observacoes', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da ultima atualizacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('observacoes', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora de criacao',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('observacoes', 'conteudo',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Conteudo da observacao',
               existing_nullable=False)
    op.alter_column('observacoes', 'equipe_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID da equipe (obrigatorio quando escopo=equipe)',
               existing_nullable=True)
    op.alter_column('observacoes', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Usuario autor da observacao',
               existing_nullable=False)
    op.alter_column('observacoes', 'numero_processo',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Numero do processo sem formatacao',
               existing_nullable=False)
    op.alter_column('observacoes', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico da observacao',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_table_comment(
        'observacao_mencoes',
        'Mencoes de usuarios em observacoes',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_historico_usuario_criado', table_name='historico_pesquisas', postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('idx_historico_usuario_criado', 'historico_pesquisas', ['usuario', sa.text('criado_em DESC')], unique=False, postgresql_where='(deletado_em IS NULL)')
    op.drop_index('idx_historico_criado_em', table_name='historico_pesquisas', postgresql_using='btree', postgresql_ops={'criado_em': 'DESC'}, postgresql_where=sa.text('deletado_em IS NULL'))
    op.create_index('idx_historico_criado_em', 'historico_pesquisas', [sa.text('criado_em DESC')], unique=False, postgresql_where='(deletado_em IS NULL)')
    op.alter_column('historico_pesquisas', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.alter_column('historico_pesquisas', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da última atualização',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('historico_pesquisas', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora de criação do registro',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('historico_pesquisas', 'caixa_contexto',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Campo de texto livre para contexto adicional',
               existing_nullable=True)
    op.alter_column('historico_pesquisas', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Identificação do usuário (email, CPF, username, etc)',
               existing_nullable=False)
    op.alter_column('historico_pesquisas', 'numero_processo_formatado',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Número do processo formatado (ex: 12345.678901/2024-99)',
               existing_nullable=True)
    op.alter_column('historico_pesquisas', 'numero_processo',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Número do processo sem formatação',
               existing_nullable=False)
    op.alter_column('historico_pesquisas', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador único da pesquisa',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('equipes', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.alter_column('equipes', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da última atualização',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('equipes', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora de criação',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('equipes', 'proprietario_usuario',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Usuário proprietário da equipe',
               existing_nullable=False)
    op.alter_column('equipes', 'descricao',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descrição da equipe',
               existing_nullable=True)
    op.alter_column('equipes', 'nome',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nome da equipe',
               existing_nullable=False)
    op.alter_column('equipes', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador único da equipe',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('equipe_membros', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.alter_column('equipe_membros', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora de criação',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('equipe_membros', 'papel',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Papel do membro na equipe (admin, member)',
               existing_nullable=False,
               existing_server_default=sa.text("'member'::character varying"))
    op.alter_column('equipe_membros', 'usuario',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Identificação do usuário membro',
               existing_nullable=False)
    op.alter_column('equipe_membros', 'equipe_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID da equipe',
               existing_nullable=False)
    op.alter_column('equipe_membros', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador único do membro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('compartilhamentos', 'deletado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora da exclusão (soft delete)',
               existing_nullable=True)
    op.alter_column('compartilhamentos', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora de criação',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('compartilhamentos', 'usuario_destino',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Usuário destino (se compartilhamento individual)',
               existing_nullable=True)
    op.alter_column('compartilhamentos', 'equipe_destino_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID da equipe destino (se compartilhamento com equipe)',
               existing_nullable=True)
    op.alter_column('compartilhamentos', 'compartilhado_por',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Usuário que compartilhou',
               existing_nullable=False)
    op.alter_column('compartilhamentos', 'tag_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID da tag compartilhada',
               existing_nullable=False)
    op.alter_column('compartilhamentos', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador único do compartilhamento',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_index('idx_situacao_processo_unique', table_name='processo_situacoes', postgresql_where=sa.text('deletado_em IS NULL'))
    op.drop_table('processo_situacoes')
    # ### end Alembic commands ###
